name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Hatch
      uses: pypa/hatch@257e27e51a6a5616ed08a39a408a21c35c9931bc
      
    - name: Run tests
      run: hatch run test
